Amend debian installation instructions
OpenTabletDriver/OpenTabletDriver.Web pull request #120
Opened 2023-10-26 18:27 UTC by jamesbt365

![image](https://github.com/OpenTabletDriver/OpenTabletDriver.Web/assets/22662856/62bc4c79-97a1-4c63-a1b4-00ac75d6c21b)
Not sure if I'm a fan of that last newline. Also no idea if "apt-transport-https" is required so I have gone ahead and removed it from the list of instructions (i don't recall having to do that on ubuntu)

2023-10-26 19:14 UTC, X9VoiD requested changes

2023-10-26 19:14 UTC, X9VoiD commented on OpenTabletDriver.Web/Views/Wiki/Install/Linux.cshtml
> +        If you are experiencing these see these solutions from microsoft
```suggestion
        If you are experiencing these see these solutions from Microsoft
```

2023-10-26 20:47 UTC, X9VoiD requested changes

2023-10-26 20:47 UTC, X9VoiD commented on OpenTabletDriver.Web/Views/Wiki/Install/Linux.cshtml
> +        Note: If you have the microsoft dotnet repository installed you will have to either make sure you are
```suggestion
        Note: If you have the Microsoft dotnet repository installed you will have to either make sure you are
```

I somehow missed this one...

2023-10-26 21:39 UTC, jamesbt365 commented on OpenTabletDriver.Web/Views/Wiki/Install/Linux.cshtml
> +        Note: If you have the microsoft dotnet repository installed you will have to either make sure you are
void is throwing

2023-11-21 20:52 UTC, jamesbt365 commented
Done on migration to opentabletdriver.github.io

2023-11-21 20:52 UTC, closed without merging