Add Administrator account warning on Window FAQ.
OpenTabletDriver/OpenTabletDriver.Web pull request #29
Opened 2021-12-31 11:50 UTC by jamesbt365

Add an Administrator account FAQ instance showing how to turn on uac.

Should an override for the warning by running OpenTabletDriver under another user be added as it is quite long as i don't know if to add the override?

2021-12-31 20:36 UTC, InfinityGhost requested changes
Formatting

2021-12-31 20:36 UTC, InfinityGhost commented on OpenTabletDriver.Web/Views/Wiki/FAQ/Windows.cshtml
> +        <p>
```suggestion
    <p>
```

2021-12-31 20:41 UTC, jamesbt365 commented
Corrected.

2022-01-04 18:04 UTC, InfinityGhost approved these changes

2022-01-04 18:05 UTC, merged