Remodel EACCESS section to be persistant.
OpenTabletDriver/OpenTabletDriver.Web pull request #76
Opened 2022-05-10 00:22 UTC by jamesbt365

fixes #32 

This is ugly and horribly formatted (much like my face), I will cleanup this pr when I have time after i wake up.

2022-05-20 20:35 UTC, InfinityGhost requested changes

2022-05-20 20:35 UTC, InfinityGhost commented on OpenTabletDriver.Web/Views/Wiki/FAQ/Linux.cshtml
> +    systemctl --user restart opentabletdriver
Fix indentation

2022-05-20 20:35 UTC, InfinityGhost commented on OpenTabletDriver.Web/Views/Wiki/FAQ/Linux.cshtml
> +    </p>
Fix formatting

2022-05-20 20:49 UTC, vedattt commented on OpenTabletDriver.Web/Views/Wiki/FAQ/Linux.cshtml
> +    </p>
```suggestion
    <p>
        This occurs usually when the udev rules are not correct, or haven't been reloaded.
        Make sure your rules are correct by heading <a href="#fail-device-streams">here</a>.
    </p>
```

2022-05-20 20:51 UTC, vedattt commented on OpenTabletDriver.Web/Views/Wiki/FAQ/Linux.cshtml
> +    systemctl --user restart opentabletdriver
```suggestion
        sudo udevadm control --reload-rules
        # Skips the step requiring a replug of the tablet.
        udevadm trigger
        # Helps ensure that OpenTabletDriver uses the tablet correctly.
        systemctl --user restart opentabletdriver
```

2022-05-20 20:52 UTC, InfinityGhost approved these changes

2022-06-03 00:26 UTC, InfinityGhost approved these changes

2022-06-03 00:26 UTC, merged