Add post-Installation instructions to both Windows and MacOS
OpenTabletDriver/OpenTabletDriver.Web pull request #89
Opened 2022-06-05 23:15 UTC by jamesbt365

2022-06-07 22:15 UTC, InfinityGhost commented
Resolve merge conflicts.

2022-06-07 22:28 UTC, jamesbt365 commented
Resolved.

2022-06-08 02:11 UTC, InfinityGhost requested changes

2022-06-08 02:11 UTC, InfinityGhost commented on OpenTabletDriver.Web/Views/Wiki/Install/Windows.cshtml
> +    </p>
Dangling `</p>` closing tag

2023-11-21 20:52 UTC, jamesbt365 commented
superseded by #120

2023-11-21 20:52 UTC, closed without merging